"""test

Revision ID: 449bca05824d
Revises: 
Create Date: 2025-09-14 07:59:00.779617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449bca05824d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=True)

    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_id'), ['id'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_name'), ['name'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_name'), ['name'], unique=False)

    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachers_name'), ['name'], unique=False)

    op.create_table('generated_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_schedules_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_schedules_id'), ['id'], unique=False)

    op.create_table('schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('weekly_hours', sa.Float(), nullable=False),
    sa.Column('week_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_items_id'), ['id'], unique=False)

    op.create_table('weekly_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_schedule_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('is_even_week', sa.Integer(), nullable=False),
    sa.Column('schedule_item_id', sa.Integer(), nullable=False),
    sa.Column('hours_even', sa.Float(), nullable=False),
    sa.Column('hours_odd', sa.Float(), nullable=False),
    sa.Column('daily_schedule', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['generated_schedule_id'], ['generated_schedules.id'], ),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['schedule_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_distributions_generated_schedule_id'), ['generated_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_distributions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_distributions_schedule_item_id'), ['schedule_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_distributions_schedule_item_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_distributions_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_distributions_generated_schedule_id'))

    op.drop_table('weekly_distributions')
    with op.batch_alter_table('schedule_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_items_id'))

    op.drop_table('schedule_items')
    with op.batch_alter_table('generated_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_schedules_id'))
        batch_op.drop_index(batch_op.f('ix_generated_schedules_group_id'))

    op.drop_table('generated_schedules')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_name'))
        batch_op.drop_index(batch_op.f('ix_teachers_id'))

    op.drop_table('teachers')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_name'))
        batch_op.drop_index(batch_op.f('ix_subjects_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_name'))
        batch_op.drop_index(batch_op.f('ix_rooms_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_id'))

    op.drop_table('holidays')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_name'))
        batch_op.drop_index(batch_op.f('ix_groups_id'))

    op.drop_table('groups')
    # ### end Alembic commands ###
